

n_process: 6

task:
  name: &task_name 'CosNet'

model:
  backbone: 'densenet121'
  #backbone: 'resnet18'
  #backbone: 'resnet34'
  #backbone: 'resnet50'
  pars:
    #n_emb: 512
    n_emb: 1024
    radius: 70
    margin: 0.35
    n_class: 5004
    drop_rate: 0.5
    pretrain: 1


train:
  #pretrained_file: 'Arc_11'
  #pretrained_file: 'Arc-coarse-resnet18'
  batch_size: 32
  batches_per_epoch: 500
  n_epoch: 600
  patience: 30
  balance: 0

val:
  cal_metric_once: True
  batch_size: 32

loss:
  #name: 'cross_entropy'

  #name: 'ArcFace'
  #radius: 70
  #margin: 0.5

  #name: 'CosFace'
  #radius: 70
  #margin: 0.35

  name: 'PNLoss'
  p_threshold: 0.6
  n_threshold: 0.05
  unknown_class: 5004

transform:
  name: 'align_transform'
  num_preprocessor: 6
  params:
    size: 320
    align: True
    align_p: 0.5

scoreboard:
  len: 11
  sort: 'inc'
  mode: 'min'

